version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"

  build-backend:
    docker: 
      - image: cimg/node:10.20
    steps:
      - checkout 
      - run: 
          name: Install Dependenices Backend
          command: |
            cd backend
            npm i
      - run: 
          name: Build Backend
          command: |
            pwd





workflows:
  default:
    jobs:
      - hello-world
      - build-backend
# TODO: backend build job and fail screen shot
# TODO: frontend build job and fail screen shot
