version: 2.1

orbs:
    slack: circleci/slack@3.4.2
    aws-cli: circleci/aws-cli@1.2.1


commands:
  install-dependencies:
    description: "Install dependencies for the given application layer (frontend/backend)"
    parameters:
      layer:
        type: string
    steps:
      - run: 
          name: Install << parameters.layer >> dependencies
          command: |
            cd << parameters.layer >> 
            npm i
      - slack/notify-on-failure

jobs:
  build-backend:
    docker: 
      - image: cimg/node:lts
    steps:
      - checkout 
      - install-dependencies:
          layer: "backend"
      - run: 
          name: Build Backend
          command: |
            cd backend
            npm run build
      - slack/notify-on-failure

  build-frontend:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - install-dependencies:
          layer: "frontend" 
      - run:
          name: Build Frontend
          command: |
            cd frontend
            npm run build
      - slack/notify-on-failure
  
  test-backend:
      docker:
          - image: cimg/node:lts
      steps:
          - checkout
          - install-dependencies:
              layer: "backend"
          - run:
              name: Unit Test Backend
              command: |
                cd backend
                mkdir -p ./reports/junit/
                npm run test:report                
              environment:
                  JEST_JUNIT_OUTPUT_DIR: "./reports/junit/"
          - store_test_results:
              path: ./backend/reports/junit/
          - slack/notify-on-failure

  test-frontend:
      docker:
          - image: cimg/node:lts
      steps:
        - checkout
        - install-dependencies:
            layer: "frontend"
        - run:
            name: Unit Test Frontend
            command: |
              cd frontend
              mkdir -p ./reports/junit/              
              npm run test:report
            environment:
              JEST_JUNIT_OUTPUT_DIR: "./reports/junit/"
        - store_test_results:
            path: ./frontend/reports/junit/
        - slack/notify-on-failure

  audit-backend-dependencies:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - install-dependencies:
          layer: "backend"
      - run:
          name: Audit backend Dependencies
          command: |
            cd backend
            npm audit --audit-level=critical
      - slack/notify-on-failure

  audit-frontend-dependencies:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - install-dependencies:
          layer: "frontend"
      - run:
         name: Audit frontend dependencies
         command: |
          cd frontend
          npm audit --audit-level=critical
      - slack/notify-on-failure

  create-infra-backend:
    executor: aws-cli/default
    steps:
      - checkout
      - run: aws s3 ls         


workflows:
  default:
    jobs:      
      # - build-backend
      # - build-frontend
      # - test-backend
      # - test-frontend
      # - audit-backend-dependencies
      # - audit-frontend-dependencies
      - create-infra-backend      
      
