version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"

workflows:
  default:
    jobs:
      - hello-world

# TODO: backend build job and fail screen shot
# TODO: frontend build job and fail screen shot