version: 2.1

jobs:
  build-backend:
    docker: 
      - image: cimg/node:lts
    steps:
      - checkout 
      - run: 
          name: Install Dependencies Backend
          command: |
            cd backend
            npm i
      - run: 
          name: Build Backend
          command: |
            cd backend
            npm run build

  build-frontend:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install Dependencies Frontend
          command: |
            cd frontend
            npm i 
      - run:
          name: Build Frontend
          command: |
            cd frontend
            npm run build

workflows:
  default:
    jobs:      
      - build-backend
      - build-frontend
