version: 2.1

jobs:
  build-backend:
    docker: 
      - image: cimg/node:10.20
    steps:
      - checkout 
      - run: 
          name: Install Dependenices Backend
          command: |
            cd backend
            npm i
      - run: 
          name: Build Backend
          command: |
            cd backend
            npm run build

workflows:
  default:
    jobs:      
      - build-backend
# TODO: backend build job and fail screen shot
# TODO: frontend build job and fail screen shot
# TODO: Build  on master only