version: 2.1

jobs:
  build-backend:
    docker: 
      - image: cimg/node:lts
    steps:
      - checkout 
      - run: 
          name: Install Dependencies Backend
          command: |
            cd backend
            npm i
      - run: 
          name: Build Backend
          command: |
            cd backend
            npm run build

  build-frontend:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install Dependencies Frontend
          command: |
            cd frontend
            npm i 
      - run:
          name: Build Frontend
          command: |
            cd frontend
            npm run build
  
  test-backend:
      docker:
          - image: cimg/node:lts
      steps:
          - checkout
          - run: 
              name: Install Dependencies Backend
              command: |
                cd backend
                npm i
          - run:
              name: Unit Test Backend
              command: |
                cd backend
                mkdir -p ./reports/junit/
                npm run test:report                
              environment:
                  JEST_JUNIT_OUTPUT_DIR: "./reports/junit/"
          - store_test_results:
              path: ./backend/reports/junit/

  test-frontend:
      docker:
          - image: cimg/node:lts
      steps:
        - checkout
        - run:
            name: Install Dependencies Frontend
            command: |
              cd frontend
              npm i
        - run:
            name: Unit Test Frontend
            command: |
              cd frontend
              mkdir -p ./reports/junit/
              npm run build
              npm run test:report
            environment:
              JEST_JUNIT_OUTPUT_DIR: "./reports/junit/"
        - store_test_results:
            path: ./frontend/reports/junit/

workflows:
  default:
    jobs:      
      - build-backend
      - build-frontend
      - test-backend
      - test-frontend
